### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by kyleplo** [destruc7i0n/extract-mcstructure#1]
I've used this program before and it worked great, but now it doesn't seem to be working for me. It is not able to find any structures in my world even though I have saved a structure. I know the structure saved properly since I can load it in using structure blocks or the `/structure` command.

**Comment by destruc7i0n** [comment]
Seems that I should have locked the `amulet_nbt` version. Should be fixed now

**Comment by destruc7i0n** [comment]
Closing this for now, feel free to re-open if you still are encountering this issue.
